#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Restoran")]
	public partial class RestoranDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertOsoblje(Osoblje instance);
    partial void UpdateOsoblje(Osoblje instance);
    partial void DeleteOsoblje(Osoblje instance);
    partial void InsertPorudzbina(Porudzbina instance);
    partial void UpdatePorudzbina(Porudzbina instance);
    partial void DeletePorudzbina(Porudzbina instance);
    partial void InsertSmena(Smena instance);
    partial void UpdateSmena(Smena instance);
    partial void DeleteSmena(Smena instance);
    partial void InsertStavka(Stavka instance);
    partial void UpdateStavka(Stavka instance);
    partial void DeleteStavka(Stavka instance);
    partial void InsertSto(Sto instance);
    partial void UpdateSto(Sto instance);
    partial void DeleteSto(Sto instance);
    #endregion
		
		public RestoranDataContext() : 
				base(global::WpfApp2.Properties.Settings.Default.RestoranConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public RestoranDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RestoranDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RestoranDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RestoranDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Istorija> Istorijas
		{
			get
			{
				return this.GetTable<Istorija>();
			}
		}
		
		public System.Data.Linq.Table<Usluga> Uslugas
		{
			get
			{
				return this.GetTable<Usluga>();
			}
		}
		
		public System.Data.Linq.Table<Osoblje> Osobljes
		{
			get
			{
				return this.GetTable<Osoblje>();
			}
		}
		
		public System.Data.Linq.Table<Porudzbina> Porudzbinas
		{
			get
			{
				return this.GetTable<Porudzbina>();
			}
		}
		
		public System.Data.Linq.Table<Smena> Smenas
		{
			get
			{
				return this.GetTable<Smena>();
			}
		}
		
		public System.Data.Linq.Table<Stavka> Stavkas
		{
			get
			{
				return this.GetTable<Stavka>();
			}
		}
		
		public System.Data.Linq.Table<Sto> Stos
		{
			get
			{
				return this.GetTable<Sto>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Istorija")]
	public partial class Istorija
	{
		
		private int _OsobljeID;
		
		private int _SmenaID;
		
		public Istorija()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OsobljeID", DbType="Int NOT NULL")]
		public int OsobljeID
		{
			get
			{
				return this._OsobljeID;
			}
			set
			{
				if ((this._OsobljeID != value))
				{
					this._OsobljeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SmenaID", DbType="Int NOT NULL")]
		public int SmenaID
		{
			get
			{
				return this._SmenaID;
			}
			set
			{
				if ((this._SmenaID != value))
				{
					this._SmenaID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usluga")]
	public partial class Usluga
	{
		
		private int _PorudzbinaID;
		
		private int _StavkaID;
		
		private int _Količina;
		
		private decimal _Ukupno;
		
		private string _Napomena;
		
		public Usluga()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PorudzbinaID", DbType="Int NOT NULL")]
		public int PorudzbinaID
		{
			get
			{
				return this._PorudzbinaID;
			}
			set
			{
				if ((this._PorudzbinaID != value))
				{
					this._PorudzbinaID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StavkaID", DbType="Int NOT NULL")]
		public int StavkaID
		{
			get
			{
				return this._StavkaID;
			}
			set
			{
				if ((this._StavkaID != value))
				{
					this._StavkaID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Količina", DbType="Int NOT NULL")]
		public int Količina
		{
			get
			{
				return this._Količina;
			}
			set
			{
				if ((this._Količina != value))
				{
					this._Količina = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ukupno", DbType="Money NOT NULL")]
		public decimal Ukupno
		{
			get
			{
				return this._Ukupno;
			}
			set
			{
				if ((this._Ukupno != value))
				{
					this._Ukupno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Napomena", DbType="NVarChar(500)")]
		public string Napomena
		{
			get
			{
				return this._Napomena;
			}
			set
			{
				if ((this._Napomena != value))
				{
					this._Napomena = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Osoblje")]
	public partial class Osoblje : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _OsobljeID;
		
		private string _Ime;
		
		private string _Prezime;
		
		private string _Uloga;
		
		private string _Kontakt;
		
		private decimal _Plata;
		
		private bool _Admin;
		
		private string _Username;
		
		private string _Password;
		
		private EntitySet<Porudzbina> _Porudzbinas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOsobljeIDChanging(int value);
    partial void OnOsobljeIDChanged();
    partial void OnImeChanging(string value);
    partial void OnImeChanged();
    partial void OnPrezimeChanging(string value);
    partial void OnPrezimeChanged();
    partial void OnUlogaChanging(string value);
    partial void OnUlogaChanged();
    partial void OnKontaktChanging(string value);
    partial void OnKontaktChanged();
    partial void OnPlataChanging(decimal value);
    partial void OnPlataChanged();
    partial void OnAdminChanging(bool value);
    partial void OnAdminChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    #endregion
		
		public Osoblje()
		{
			this._Porudzbinas = new EntitySet<Porudzbina>(new Action<Porudzbina>(this.attach_Porudzbinas), new Action<Porudzbina>(this.detach_Porudzbinas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OsobljeID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int OsobljeID
		{
			get
			{
				return this._OsobljeID;
			}
			set
			{
				if ((this._OsobljeID != value))
				{
					this.OnOsobljeIDChanging(value);
					this.SendPropertyChanging();
					this._OsobljeID = value;
					this.SendPropertyChanged("OsobljeID");
					this.OnOsobljeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ime", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Ime
		{
			get
			{
				return this._Ime;
			}
			set
			{
				if ((this._Ime != value))
				{
					this.OnImeChanging(value);
					this.SendPropertyChanging();
					this._Ime = value;
					this.SendPropertyChanged("Ime");
					this.OnImeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prezime", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Prezime
		{
			get
			{
				return this._Prezime;
			}
			set
			{
				if ((this._Prezime != value))
				{
					this.OnPrezimeChanging(value);
					this.SendPropertyChanging();
					this._Prezime = value;
					this.SendPropertyChanged("Prezime");
					this.OnPrezimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Uloga", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Uloga
		{
			get
			{
				return this._Uloga;
			}
			set
			{
				if ((this._Uloga != value))
				{
					this.OnUlogaChanging(value);
					this.SendPropertyChanging();
					this._Uloga = value;
					this.SendPropertyChanged("Uloga");
					this.OnUlogaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kontakt", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string Kontakt
		{
			get
			{
				return this._Kontakt;
			}
			set
			{
				if ((this._Kontakt != value))
				{
					this.OnKontaktChanging(value);
					this.SendPropertyChanging();
					this._Kontakt = value;
					this.SendPropertyChanged("Kontakt");
					this.OnKontaktChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Plata", DbType="Money NOT NULL")]
		public decimal Plata
		{
			get
			{
				return this._Plata;
			}
			set
			{
				if ((this._Plata != value))
				{
					this.OnPlataChanging(value);
					this.SendPropertyChanging();
					this._Plata = value;
					this.SendPropertyChanged("Plata");
					this.OnPlataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admin", DbType="Bit NOT NULL")]
		public bool Admin
		{
			get
			{
				return this._Admin;
			}
			set
			{
				if ((this._Admin != value))
				{
					this.OnAdminChanging(value);
					this.SendPropertyChanging();
					this._Admin = value;
					this.SendPropertyChanged("Admin");
					this.OnAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Osoblje_Porudzbina", Storage="_Porudzbinas", ThisKey="OsobljeID", OtherKey="OsobljeID")]
		public EntitySet<Porudzbina> Porudzbinas
		{
			get
			{
				return this._Porudzbinas;
			}
			set
			{
				this._Porudzbinas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Porudzbinas(Porudzbina entity)
		{
			this.SendPropertyChanging();
			entity.Osoblje = this;
		}
		
		private void detach_Porudzbinas(Porudzbina entity)
		{
			this.SendPropertyChanging();
			entity.Osoblje = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Porudzbina")]
	public partial class Porudzbina : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PorudzbinaID;
		
		private int _StoID;
		
		private int _OsobljeID;
		
		private System.DateTime _VremePorudzbine;
		
		private bool _Zavrseno;
		
		private EntityRef<Osoblje> _Osoblje;
		
		private EntityRef<Sto> _Sto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPorudzbinaIDChanging(int value);
    partial void OnPorudzbinaIDChanged();
    partial void OnStoIDChanging(int value);
    partial void OnStoIDChanged();
    partial void OnOsobljeIDChanging(int value);
    partial void OnOsobljeIDChanged();
    partial void OnVremePorudzbineChanging(System.DateTime value);
    partial void OnVremePorudzbineChanged();
    partial void OnZavrsenoChanging(bool value);
    partial void OnZavrsenoChanged();
    #endregion
		
		public Porudzbina()
		{
			this._Osoblje = default(EntityRef<Osoblje>);
			this._Sto = default(EntityRef<Sto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PorudzbinaID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PorudzbinaID
		{
			get
			{
				return this._PorudzbinaID;
			}
			set
			{
				if ((this._PorudzbinaID != value))
				{
					this.OnPorudzbinaIDChanging(value);
					this.SendPropertyChanging();
					this._PorudzbinaID = value;
					this.SendPropertyChanged("PorudzbinaID");
					this.OnPorudzbinaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoID", DbType="Int NOT NULL")]
		public int StoID
		{
			get
			{
				return this._StoID;
			}
			set
			{
				if ((this._StoID != value))
				{
					if (this._Sto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnStoIDChanging(value);
					this.SendPropertyChanging();
					this._StoID = value;
					this.SendPropertyChanged("StoID");
					this.OnStoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OsobljeID", DbType="Int NOT NULL")]
		public int OsobljeID
		{
			get
			{
				return this._OsobljeID;
			}
			set
			{
				if ((this._OsobljeID != value))
				{
					if (this._Osoblje.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnOsobljeIDChanging(value);
					this.SendPropertyChanging();
					this._OsobljeID = value;
					this.SendPropertyChanged("OsobljeID");
					this.OnOsobljeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VremePorudzbine", DbType="SmallDateTime NOT NULL")]
		public System.DateTime VremePorudzbine
		{
			get
			{
				return this._VremePorudzbine;
			}
			set
			{
				if ((this._VremePorudzbine != value))
				{
					this.OnVremePorudzbineChanging(value);
					this.SendPropertyChanging();
					this._VremePorudzbine = value;
					this.SendPropertyChanged("VremePorudzbine");
					this.OnVremePorudzbineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zavrseno", DbType="Bit NOT NULL")]
		public bool Zavrseno
		{
			get
			{
				return this._Zavrseno;
			}
			set
			{
				if ((this._Zavrseno != value))
				{
					this.OnZavrsenoChanging(value);
					this.SendPropertyChanging();
					this._Zavrseno = value;
					this.SendPropertyChanged("Zavrseno");
					this.OnZavrsenoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Osoblje_Porudzbina", Storage="_Osoblje", ThisKey="OsobljeID", OtherKey="OsobljeID", IsForeignKey=true)]
		public Osoblje Osoblje
		{
			get
			{
				return this._Osoblje.Entity;
			}
			set
			{
				Osoblje previousValue = this._Osoblje.Entity;
				if (((previousValue != value) 
							|| (this._Osoblje.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Osoblje.Entity = null;
						previousValue.Porudzbinas.Remove(this);
					}
					this._Osoblje.Entity = value;
					if ((value != null))
					{
						value.Porudzbinas.Add(this);
						this._OsobljeID = value.OsobljeID;
					}
					else
					{
						this._OsobljeID = default(int);
					}
					this.SendPropertyChanged("Osoblje");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sto_Porudzbina", Storage="_Sto", ThisKey="StoID", OtherKey="StoID", IsForeignKey=true)]
		public Sto Sto
		{
			get
			{
				return this._Sto.Entity;
			}
			set
			{
				Sto previousValue = this._Sto.Entity;
				if (((previousValue != value) 
							|| (this._Sto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Sto.Entity = null;
						previousValue.Porudzbinas.Remove(this);
					}
					this._Sto.Entity = value;
					if ((value != null))
					{
						value.Porudzbinas.Add(this);
						this._StoID = value.StoID;
					}
					else
					{
						this._StoID = default(int);
					}
					this.SendPropertyChanged("Sto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Smena")]
	public partial class Smena : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SmenaID;
		
		private System.DateTime _Datum;
		
		private System.TimeSpan _PocetakSmene;
		
		private System.TimeSpan _KrajSmene;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSmenaIDChanging(int value);
    partial void OnSmenaIDChanged();
    partial void OnDatumChanging(System.DateTime value);
    partial void OnDatumChanged();
    partial void OnPocetakSmeneChanging(System.TimeSpan value);
    partial void OnPocetakSmeneChanged();
    partial void OnKrajSmeneChanging(System.TimeSpan value);
    partial void OnKrajSmeneChanged();
    #endregion
		
		public Smena()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SmenaID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SmenaID
		{
			get
			{
				return this._SmenaID;
			}
			set
			{
				if ((this._SmenaID != value))
				{
					this.OnSmenaIDChanging(value);
					this.SendPropertyChanging();
					this._SmenaID = value;
					this.SendPropertyChanged("SmenaID");
					this.OnSmenaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Datum", DbType="Date NOT NULL")]
		public System.DateTime Datum
		{
			get
			{
				return this._Datum;
			}
			set
			{
				if ((this._Datum != value))
				{
					this.OnDatumChanging(value);
					this.SendPropertyChanging();
					this._Datum = value;
					this.SendPropertyChanged("Datum");
					this.OnDatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PocetakSmene", DbType="Time NOT NULL")]
		public System.TimeSpan PocetakSmene
		{
			get
			{
				return this._PocetakSmene;
			}
			set
			{
				if ((this._PocetakSmene != value))
				{
					this.OnPocetakSmeneChanging(value);
					this.SendPropertyChanging();
					this._PocetakSmene = value;
					this.SendPropertyChanged("PocetakSmene");
					this.OnPocetakSmeneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KrajSmene", DbType="Time NOT NULL")]
		public System.TimeSpan KrajSmene
		{
			get
			{
				return this._KrajSmene;
			}
			set
			{
				if ((this._KrajSmene != value))
				{
					this.OnKrajSmeneChanging(value);
					this.SendPropertyChanging();
					this._KrajSmene = value;
					this.SendPropertyChanged("KrajSmene");
					this.OnKrajSmeneChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Stavka")]
	public partial class Stavka : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _StavkaID;
		
		private string _Naziv;
		
		private string _Kategorija;
		
		private decimal _Cena;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStavkaIDChanging(int value);
    partial void OnStavkaIDChanged();
    partial void OnNazivChanging(string value);
    partial void OnNazivChanged();
    partial void OnKategorijaChanging(string value);
    partial void OnKategorijaChanged();
    partial void OnCenaChanging(decimal value);
    partial void OnCenaChanged();
    #endregion
		
		public Stavka()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StavkaID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int StavkaID
		{
			get
			{
				return this._StavkaID;
			}
			set
			{
				if ((this._StavkaID != value))
				{
					this.OnStavkaIDChanging(value);
					this.SendPropertyChanging();
					this._StavkaID = value;
					this.SendPropertyChanged("StavkaID");
					this.OnStavkaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Naziv", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Naziv
		{
			get
			{
				return this._Naziv;
			}
			set
			{
				if ((this._Naziv != value))
				{
					this.OnNazivChanging(value);
					this.SendPropertyChanging();
					this._Naziv = value;
					this.SendPropertyChanged("Naziv");
					this.OnNazivChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kategorija", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Kategorija
		{
			get
			{
				return this._Kategorija;
			}
			set
			{
				if ((this._Kategorija != value))
				{
					this.OnKategorijaChanging(value);
					this.SendPropertyChanging();
					this._Kategorija = value;
					this.SendPropertyChanged("Kategorija");
					this.OnKategorijaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cena", DbType="Money NOT NULL")]
		public decimal Cena
		{
			get
			{
				return this._Cena;
			}
			set
			{
				if ((this._Cena != value))
				{
					this.OnCenaChanging(value);
					this.SendPropertyChanging();
					this._Cena = value;
					this.SendPropertyChanged("Cena");
					this.OnCenaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sto")]
	public partial class Sto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _StoID;
		
		private int _Kapacitet;
		
		private string _Lokacija;
		
		private bool _Rezervisano;
		
		private string _Napomena;
		
		private EntitySet<Porudzbina> _Porudzbinas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStoIDChanging(int value);
    partial void OnStoIDChanged();
    partial void OnKapacitetChanging(int value);
    partial void OnKapacitetChanged();
    partial void OnLokacijaChanging(string value);
    partial void OnLokacijaChanged();
    partial void OnRezervisanoChanging(bool value);
    partial void OnRezervisanoChanged();
    partial void OnNapomenaChanging(string value);
    partial void OnNapomenaChanged();
    #endregion
		
		public Sto()
		{
			this._Porudzbinas = new EntitySet<Porudzbina>(new Action<Porudzbina>(this.attach_Porudzbinas), new Action<Porudzbina>(this.detach_Porudzbinas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int StoID
		{
			get
			{
				return this._StoID;
			}
			set
			{
				if ((this._StoID != value))
				{
					this.OnStoIDChanging(value);
					this.SendPropertyChanging();
					this._StoID = value;
					this.SendPropertyChanged("StoID");
					this.OnStoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kapacitet", DbType="Int NOT NULL")]
		public int Kapacitet
		{
			get
			{
				return this._Kapacitet;
			}
			set
			{
				if ((this._Kapacitet != value))
				{
					this.OnKapacitetChanging(value);
					this.SendPropertyChanging();
					this._Kapacitet = value;
					this.SendPropertyChanged("Kapacitet");
					this.OnKapacitetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lokacija", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Lokacija
		{
			get
			{
				return this._Lokacija;
			}
			set
			{
				if ((this._Lokacija != value))
				{
					this.OnLokacijaChanging(value);
					this.SendPropertyChanging();
					this._Lokacija = value;
					this.SendPropertyChanged("Lokacija");
					this.OnLokacijaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rezervisano", DbType="Bit NOT NULL")]
		public bool Rezervisano
		{
			get
			{
				return this._Rezervisano;
			}
			set
			{
				if ((this._Rezervisano != value))
				{
					this.OnRezervisanoChanging(value);
					this.SendPropertyChanging();
					this._Rezervisano = value;
					this.SendPropertyChanged("Rezervisano");
					this.OnRezervisanoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Napomena", DbType="NVarChar(100)")]
		public string Napomena
		{
			get
			{
				return this._Napomena;
			}
			set
			{
				if ((this._Napomena != value))
				{
					this.OnNapomenaChanging(value);
					this.SendPropertyChanging();
					this._Napomena = value;
					this.SendPropertyChanged("Napomena");
					this.OnNapomenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sto_Porudzbina", Storage="_Porudzbinas", ThisKey="StoID", OtherKey="StoID")]
		public EntitySet<Porudzbina> Porudzbinas
		{
			get
			{
				return this._Porudzbinas;
			}
			set
			{
				this._Porudzbinas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Porudzbinas(Porudzbina entity)
		{
			this.SendPropertyChanging();
			entity.Sto = this;
		}
		
		private void detach_Porudzbinas(Porudzbina entity)
		{
			this.SendPropertyChanging();
			entity.Sto = null;
		}
	}
}
#pragma warning restore 1591
